export const ROUTES = {
  LOGIN: '/login',
  HOME: '/',
  SPREADSHEET: '/planilha',
  AGENDA: '/agenda',
  LIST: '/lista',
  TASKS: '/tarefas-fiscal',
  MY_TASKS: '/minhas-tarefas',
  DEPARTMENT_DASHBOARD: '/dashboard-departamento',
  ORGANIZATION_DASHBOARD: '/dashboard-geral',
  ROUTINES: '/rotinas',
  ROUTINE_CREATE: '/rotinas/nova',
  ROUTINE_DETAILS: '/rotinas/:routineId',
  COMPANIES: '/empresas',
  COMPANY_CREATE: '/empresas/nova',
  COMPANY_DETAILS: '/empresas/:clientId',
  EMPLOYEES: '/funcionarios',
  EMPLOYEE_CREATE: '/funcionarios/novo',
  SCREENS: '/telas',
  SCREEN_CREATE: '/telas/nova',
  ROLES: '/cargos',
  SETTINGS: '/configuracoes',
  PROFILE: '/perfil',
} as const
