export const ROUTES = {
  LOGIN: '/login',
  HOME: '/',
  SPREADSHEET: '/planilha',
  LIST: '/lista',
  TASKS: '/tarefas-fiscal',
  MY_TASKS: '/minhas-tarefas',
  DEPARTMENT_DASHBOARD: '/dashboard-departamento',
  MANAGER_DASHBOARD: '/dashboard-geral',
  ROUTINES: '/rotinas',
  COMPANIES: '/empresas',
  EMPLOYEES: '/funcionarios',
  ROLES: '/cargos',
  PROFILE: '/perfil',
} as const
