import { ROUTINE_STATUS } from '../../../constants/routineStatus'
import type {
  Department,
  Employee,
  RoutineListItem,
} from '../../../types/domain'

export const routineListSampleRoutine = {
  id: 'routine-enviar-das',
  departmentId: 'dept-fiscal',
  name: 'Enviar DAS',
  shortName: 'Enviar DAS',
  description:
    'Envio da guia mensal do Simples Nacional apos conferencia e apuracao.',
  departmentName: 'Fiscal',
  period: '2026-06',
}

export const routineListSampleDepartment: Department = {
  id: 'dept-fiscal',
  name: 'Fiscal',
}

export const routineListSampleEmployees: Employee[] = [
  { id: 'employee-001', name: 'Ana Souza' },
  { id: 'employee-002', name: 'Bruno Lima' },
  { id: 'employee-003', name: 'Carla Melo' },
]

export const routineListSampleItems = [
  {
    id: 'list-send-das-001',
    companyCode: '001',
    companyName: 'Aurora Comercio Ltda.',
    status: ROUTINE_STATUS.COMPLETED,
    dueDate: '2026-06-18',
    assigneeId: 'employee-001',
    assigneeName: 'Ana Souza',
    notes: 'Guia enviada e confirmada pelo cliente.',
    indicators: { attachments: 2, comments: 1 },
  },
  {
    id: 'list-send-das-002',
    companyCode: '002',
    companyName: 'Bento Arquitetura',
    status: ROUTINE_STATUS.PENDING,
    dueDate: '2026-06-24',
    assigneeId: 'employee-001',
    assigneeName: 'Ana Souza',
    notes: 'Aguardando conferencia final.',
    indicators: { attachments: 0, comments: 0 },
  },
  {
    id: 'list-send-das-003',
    companyCode: '003',
    companyName: 'Cais Tecnologia S.A.',
    status: ROUTINE_STATUS.COMPLETED,
    dueDate: '2026-06-18',
    assigneeId: 'employee-003',
    assigneeName: 'Carla Melo',
    notes: 'Envio realizado antes do prazo.',
    indicators: { attachments: 3, comments: 0 },
  },
  {
    id: 'list-send-das-004',
    companyCode: '004',
    companyName: 'Dalia Servicos Medicos',
    status: ROUTINE_STATUS.ERROR,
    dueDate: '2026-06-18',
    assigneeId: 'employee-002',
    assigneeName: 'Bruno Lima',
    notes: 'Arquivo do cliente com divergencia.',
    indicators: { attachments: 1, comments: 4 },
  },
  {
    id: 'list-send-das-005',
    companyCode: '005',
    companyName: 'Estrela Alimentos Eireli',
    status: ROUTINE_STATUS.IN_PROGRESS,
    dueDate: '2026-06-21',
    assigneeId: 'employee-001',
    assigneeName: 'Ana Souza',
    notes: 'Conferencia de vencimento em andamento.',
    indicators: { attachments: 1, comments: 2 },
  },
  {
    id: 'list-send-das-006',
    companyCode: '006',
    companyName: 'Forte Engenharia Ltda.',
    status: ROUTINE_STATUS.PENDING,
    dueDate: '2026-06-23',
    assigneeId: 'employee-003',
    assigneeName: 'Carla Melo',
    notes: '',
    indicators: { attachments: 0, comments: 1 },
  },
  {
    id: 'list-send-das-007',
    companyCode: '007',
    companyName: 'Granito Transportes',
    status: ROUTINE_STATUS.ERROR,
    dueDate: '2026-06-19',
    assigneeId: 'employee-002',
    assigneeName: 'Bruno Lima',
    notes: 'Cliente solicitou revisao do valor.',
    indicators: { attachments: 2, comments: 3 },
  },
  {
    id: 'list-send-das-008',
    companyCode: '008',
    companyName: 'Horizonte Clinica Popular',
    status: ROUTINE_STATUS.IN_PROGRESS,
    dueDate: '2026-06-22',
    assigneeId: 'employee-001',
    assigneeName: 'Ana Souza',
    notes: 'Guia gerada, falta envio.',
    indicators: { attachments: 1, comments: 0 },
  },
  {
    id: 'list-send-das-009',
    companyCode: '009',
    companyName: 'Ipiranga Servicos Digitais',
    status: ROUTINE_STATUS.PENDING,
    dueDate: '2026-06-25',
    assigneeId: 'employee-003',
    assigneeName: 'Carla Melo',
    notes: 'Sem pendencias registradas.',
    indicators: { attachments: 0, comments: 0 },
  },
  {
    id: 'list-send-das-010',
    companyCode: '010',
    companyName: 'Jardim Moveis Planejados',
    status: ROUTINE_STATUS.COMPLETED,
    dueDate: '2026-06-20',
    assigneeId: 'employee-002',
    assigneeName: 'Bruno Lima',
    notes: 'Comprovante anexado.',
    indicators: { attachments: 2, comments: 1 },
  },
  {
    id: 'list-send-das-011',
    companyCode: '011',
    companyName: 'Kairos Consultoria',
    status: ROUTINE_STATUS.PENDING,
    dueDate: '2026-06-26',
    assigneeId: 'employee-001',
    assigneeName: 'Ana Souza',
    notes: 'Aguardando retorno do cliente.',
    indicators: { attachments: 0, comments: 2 },
  },
  {
    id: 'list-send-das-012',
    companyCode: '012',
    companyName: 'Lumina Eventos',
    status: ROUTINE_STATUS.ERROR,
    dueDate: '2026-06-20',
    assigneeId: 'employee-003',
    assigneeName: 'Carla Melo',
    notes: 'Divergencia no faturamento informado.',
    indicators: { attachments: 1, comments: 5 },
  },
]

export function buildRoutineListSampleItems(): RoutineListItem[] {
  return routineListSampleItems.map((item) => ({
    ...item,
    client: {
      id: `sample-client-${item.companyCode}`,
      code: item.companyCode,
      name: item.companyName,
    },
    routine: routineListSampleRoutine,
    department: routineListSampleDepartment,
    task: {
      id: item.id,
      kind: 'scheduled',
      clientId: `sample-client-${item.companyCode}`,
      routineId: routineListSampleRoutine.id,
      departmentId: routineListSampleRoutine.departmentId,
      assigneeId: item.assigneeId,
      status: item.status,
      period: routineListSampleRoutine.period,
      dueDate: item.dueDate,
      completedAt:
        item.status === ROUTINE_STATUS.COMPLETED
          ? `${item.dueDate}T16:00:00-03:00`
          : null,
      notes: item.notes,
      indicators: item.indicators,
    },
    originType: 'routine',
    primaryLabel: item.companyName,
    title: item.companyName,
    routineName: routineListSampleRoutine.name,
    departmentName: routineListSampleRoutine.departmentName,
    period: routineListSampleRoutine.period,
    statusDetailLabel: '',
  }))
}
